package DTO;


import javax.swing.JFrame;
import javax.swing.JOptionPane;





/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Onur Akbal-Emre Ertekin
 */
public class AnaMenu extends javax.swing.JFrame {

    /**
     * Creates new form AnaMenu
     */
    public AnaMenu() {
        super("Kütüphanem Ana Menü");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblLogo = new javax.swing.JLabel();
        islemlerpnl = new javax.swing.JPanel();
        lblYeniKitap = new javax.swing.JLabel();
        btnYeniKitap = new javax.swing.JButton();
        btnYeniOgrenci = new javax.swing.JButton();
        lblYeniOgrenci = new javax.swing.JLabel();
        btnKitapVer = new javax.swing.JButton();
        lblKitapVer = new javax.swing.JLabel();
        btnKitapAl = new javax.swing.JButton();
        lblKitapAl = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        exit = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        anamenubar = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuCikis = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        islemlerpnl.setBackground(new java.awt.Color(30, 39, 46));

        lblYeniKitap.setForeground(new java.awt.Color(255, 255, 255));
        lblYeniKitap.setText("Kitap İşlemleri");

        btnYeniKitap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconlar/iconsdss8-open-book-100.png"))); // NOI18N
        btnYeniKitap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnYeniKitapActionPerformed(evt);
            }
        });

        btnYeniOgrenci.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconlar/icons8-student-registration-100.png"))); // NOI18N
        btnYeniOgrenci.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnYeniOgrenciActionPerformed(evt);
            }
        });

        lblYeniOgrenci.setForeground(new java.awt.Color(255, 255, 255));
        lblYeniOgrenci.setText("Öğrenci İşlemleri");

        btnKitapVer.setForeground(new java.awt.Color(255, 255, 255));
        btnKitapVer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconlar/asdasdas.png"))); // NOI18N
        btnKitapVer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKitapVerActionPerformed(evt);
            }
        });

        lblKitapVer.setForeground(new java.awt.Color(255, 255, 255));
        lblKitapVer.setText("Kitap Al");

        btnKitapAl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconlar/icons8-assignment-return-100.png"))); // NOI18N
        btnKitapAl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKitapAlActionPerformed(evt);
            }
        });

        lblKitapAl.setForeground(new java.awt.Color(255, 255, 255));
        lblKitapAl.setText("Teslim Et");

        javax.swing.GroupLayout islemlerpnlLayout = new javax.swing.GroupLayout(islemlerpnl);
        islemlerpnl.setLayout(islemlerpnlLayout);
        islemlerpnlLayout.setHorizontalGroup(
            islemlerpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(islemlerpnlLayout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(islemlerpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(btnYeniKitap)
                    .addComponent(lblYeniKitap))
                .addGroup(islemlerpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(islemlerpnlLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(btnYeniOgrenci)
                        .addGap(18, 18, 18)
                        .addComponent(btnKitapAl))
                    .addGroup(islemlerpnlLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(lblYeniOgrenci)
                        .addGap(70, 70, 70)
                        .addComponent(lblKitapVer)))
                .addGap(28, 28, 28)
                .addGroup(islemlerpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnKitapVer)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, islemlerpnlLayout.createSequentialGroup()
                        .addComponent(lblKitapAl)
                        .addGap(42, 42, 42)))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        islemlerpnlLayout.setVerticalGroup(
            islemlerpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(islemlerpnlLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(islemlerpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnYeniKitap)
                    .addComponent(btnYeniOgrenci)
                    .addComponent(btnKitapAl)
                    .addComponent(btnKitapVer))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(islemlerpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblYeniKitap)
                    .addComponent(lblYeniOgrenci)
                    .addComponent(lblKitapVer)
                    .addComponent(lblKitapAl))
                .addContainerGap(65, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(210, 218, 226));
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel1MouseDragged(evt);
            }
        });
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconlar/Untitled-5.png"))); // NOI18N

        exit.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        exit.setText("X");
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                exitMousePressed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel3.setText("-");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Gabriola", 0, 18)); // NOI18N
        jLabel2.setText(" designed by Onur Akbal - Emre Ertekin");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(exit, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 14, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(exit, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2))
        );

        jMenu1.setText("Dosya");

        menuCikis.setText("Çıkış");
        menuCikis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCikisActionPerformed(evt);
            }
        });
        jMenu1.add(menuCikis);

        anamenubar.add(jMenu1);

        setJMenuBar(anamenubar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblLogo)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(islemlerpnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblLogo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(islemlerpnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        setSize(new java.awt.Dimension(712, 328));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void menuCikisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCikisActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        Giris yeni = new Giris();
        yeni.setVisible(true);
    }//GEN-LAST:event_menuCikisActionPerformed

    private void btnYeniKitapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnYeniKitapActionPerformed
        // TODO add your handling code here:
        if (Giris.durum==0) {
            JOptionPane.showMessageDialog(null, "Öğrenci Olduğunuz için bu işlemi yapamazsınız");
        }
        else{
            setVisible(false);
            Kitaplar yeni = new Kitaplar();
            yeni.setVisible(true);
        }
        
    }//GEN-LAST:event_btnYeniKitapActionPerformed

    private void btnYeniOgrenciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnYeniOgrenciActionPerformed
        // TODO add your handling code here:
        if (Giris.durum==0) {
            JOptionPane.showMessageDialog(null, "Öğrenci Olduğunuz için bu işlemi yapamazsınız");
        }
        else{
        setVisible(false);
        Ogrenciler yeni = new Ogrenciler();
        yeni.setVisible(true);
        }
    }//GEN-LAST:event_btnYeniOgrenciActionPerformed

    private void btnKitapVerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKitapVerActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        KitapVer yeni = new KitapVer();
        yeni.setVisible(true);
    }//GEN-LAST:event_btnKitapVerActionPerformed

    private void btnKitapAlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKitapAlActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        KitapAl yeni = new KitapAl();
        yeni.setVisible(true);
    }//GEN-LAST:event_btnKitapAlActionPerformed

    private void exitMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMousePressed
       System.exit(0);        
    }//GEN-LAST:event_exitMousePressed

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabel3MouseClicked
    int x,y;
    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed
        x=evt.getX();
        y=evt.getY();
    }//GEN-LAST:event_jPanel1MousePressed

    private void jPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseDragged
       int xx= evt.getXOnScreen();
       int yy= evt.getYOnScreen();
       this.setLocation(xx-x,yy-y);
    }//GEN-LAST:event_jPanel1MouseDragged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AnaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AnaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AnaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AnaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AnaMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar anamenubar;
    private javax.swing.JButton btnKitapAl;
    private javax.swing.JButton btnKitapVer;
    public javax.swing.JButton btnYeniKitap;
    private javax.swing.JButton btnYeniOgrenci;
    private javax.swing.JLabel exit;
    private javax.swing.JPanel islemlerpnl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblKitapAl;
    private javax.swing.JLabel lblKitapVer;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblYeniKitap;
    private javax.swing.JLabel lblYeniOgrenci;
    private javax.swing.JMenuItem menuCikis;
    // End of variables declaration//GEN-END:variables
}
