package DTO;

import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import net.proteanit.sql.DbUtils;
import Degiskenler.KitapHareketleri;
import Degiskenler.Kitapp;
import Degiskenler.Uye;
import Fonksiyonlar.KitapGuncelle;
import Fonksiyonlar.KitapFonksiyonlari;
import Fonksiyonlar.OgrenciFonksiyonlari;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Onur Akbal-Emre Ertekin
 */
public class KitapVer extends javax.swing.JFrame {
    /**
     * Creates new form KitapVer
     */
    OgrenciFonksiyonlari ogr = new OgrenciFonksiyonlari();
    KitapFonksiyonlari kitap = new KitapFonksiyonlari();
    public KitapVer() {
        super("Emanet Kitap Ver");
        initComponents();
        ogrenciTable.setModel(DbUtils.resultSetToTableModel(ogr.listele()));
        kitapTable.setModel(DbUtils.resultSetToTableModel(kitap.stokListele()));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kitapVerPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnVer = new javax.swing.JButton();
        btngeri = new javax.swing.JButton();
        dateverilistarihi = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        ogrenciTable = new javax.swing.JTable();
        btnOgrSec = new javax.swing.JButton();
        btnKitapSeç = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        kitapTable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        secilenOgrenci = new javax.swing.JLabel();
        secılenKitap = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Veriliş Tarihi");

        btnVer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconlar/icons8-book-stack-24.png"))); // NOI18N
        btnVer.setText("Kitap Al");
        btnVer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerActionPerformed(evt);
            }
        });

        btngeri.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconlar/icons8-return-24.png"))); // NOI18N
        btngeri.setText("Geri");
        btngeri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btngeriActionPerformed(evt);
            }
        });

        ogrenciTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(ogrenciTable);

        btnOgrSec.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconlar/icons8-student-registration-24.png"))); // NOI18N
        btnOgrSec.setText("Öğrenci Seç");
        btnOgrSec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOgrSecActionPerformed(evt);
            }
        });

        btnKitapSeç.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconlar/icons8-add-book-24.png"))); // NOI18N
        btnKitapSeç.setText("Kitap Seç");
        btnKitapSeç.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKitapSeçActionPerformed(evt);
            }
        });

        kitapTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(kitapTable);

        jLabel2.setText("Öğrenciler");

        jLabel3.setText("Kitaplar");

        javax.swing.GroupLayout kitapVerPanelLayout = new javax.swing.GroupLayout(kitapVerPanel);
        kitapVerPanel.setLayout(kitapVerPanelLayout);
        kitapVerPanelLayout.setHorizontalGroup(
            kitapVerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kitapVerPanelLayout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addGroup(kitapVerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kitapVerPanelLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(kitapVerPanelLayout.createSequentialGroup()
                        .addGap(392, 392, 392)
                        .addComponent(btnOgrSec, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnKitapSeç, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kitapVerPanelLayout.createSequentialGroup()
                        .addGap(0, 1, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(kitapVerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(kitapVerPanelLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(secilenOgrenci, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(kitapVerPanelLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(secılenKitap, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kitapVerPanelLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addGroup(kitapVerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(kitapVerPanelLayout.createSequentialGroup()
                                        .addComponent(btnVer)
                                        .addGap(26, 26, 26)
                                        .addComponent(btngeri, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(dateverilistarihi, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGroup(kitapVerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kitapVerPanelLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel3)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kitapVerPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(20, Short.MAX_VALUE))))
        );
        kitapVerPanelLayout.setVerticalGroup(
            kitapVerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kitapVerPanelLayout.createSequentialGroup()
                .addGroup(kitapVerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(kitapVerPanelLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(kitapVerPanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(kitapVerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGroup(kitapVerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(kitapVerPanelLayout.createSequentialGroup()
                                .addGroup(kitapVerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnOgrSec)
                                    .addComponent(btnKitapSeç))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(secilenOgrenci)
                                .addGap(3, 3, 3)
                                .addComponent(secılenKitap)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(kitapVerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(dateverilistarihi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(kitapVerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnVer)
                                    .addComponent(btngeri)))
                            .addGroup(kitapVerPanelLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(479, Short.MAX_VALUE))
        );

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel9.setText("Kitap Alma");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(kitapVerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(kitapVerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(1146, 441));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btngeriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btngeriActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        AnaMenu yeni = new AnaMenu();
        yeni.setVisible(true);
    }//GEN-LAST:event_btngeriActionPerformed

    private void btnVerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerActionPerformed
        // TODO add your handling code here:
        KitapHareketleri hazirla = new KitapHareketleri();
        hazirla.Kit_Id = secilenkit;
        hazirla.Uye_Id = secilenogr;
        hazirla.Ad = secilenAd;
        hazirla.KitapAdi = secilenKitap;
        
        SimpleDateFormat dateFormat = new SimpleDateFormat("dd-MM-yyyy");
        String tarih = dateFormat.format(dateverilistarihi.getDate());
        hazirla.VerilisTarihi = tarih;
        KitapGuncelle gonder = new KitapGuncelle();
        gonder.ekle(hazirla);
    }//GEN-LAST:event_btnVerActionPerformed
    int secilenogr;
    String secilenAd;
    private void btnOgrSecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOgrSecActionPerformed
        // TODO add your handling code here:
        int tablosatir= ogrenciTable.getSelectedRow();//Hangi satır olduğunu alıyor.
        secilenogr=(int) ogrenciTable.getValueAt(tablosatir,0);
        secilenAd= ogrenciTable.getValueAt(tablosatir, 1).toString();
        OgrenciFonksiyonlari getir = new OgrenciFonksiyonlari();
        Uye gelen = getir.ogrenciGetir(secilenogr);
        secilenOgrenci.setText("Secilen Ogrencı: "+gelen.isim);
        JOptionPane.showMessageDialog(null, "Seçilen Öğrenci: "+gelen.isim);
    }//GEN-LAST:event_btnOgrSecActionPerformed
    int secilenkit;
    String secilenKitap;
    private void btnKitapSeçActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKitapSeçActionPerformed
        // TODO add your handling code here:
        int tablosatir= kitapTable.getSelectedRow();//Hangi satır olduğunu alıyor.
        secilenkit=(int) kitapTable.getValueAt(tablosatir,0);
        secilenKitap=kitapTable.getValueAt(tablosatir, 1).toString();
        KitapFonksiyonlari getir = new KitapFonksiyonlari();
        Kitapp gelen = getir.kitapGetir(secilenkit);
        secılenKitap.setText("Secilen Kitap: "+gelen.isim);
        JOptionPane.showMessageDialog(null, "Seçilen Kitap: "+gelen.isim);
    }//GEN-LAST:event_btnKitapSeçActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KitapVer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KitapVer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KitapVer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KitapVer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KitapVer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKitapSeç;
    private javax.swing.JButton btnOgrSec;
    private javax.swing.JButton btnVer;
    private javax.swing.JButton btngeri;
    private com.toedter.calendar.JDateChooser dateverilistarihi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable kitapTable;
    private javax.swing.JPanel kitapVerPanel;
    private javax.swing.JTable ogrenciTable;
    private javax.swing.JLabel secilenOgrenci;
    private javax.swing.JLabel secılenKitap;
    // End of variables declaration//GEN-END:variables
}
