package DTO;






import DOA.DatabaseBaglanti;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import net.proteanit.sql.DbUtils;
import Degiskenler.KitapHareketleri;
import Degiskenler.Kitapp;
import Degiskenler.Uye;
import Fonksiyonlar.KitapGuncelle;
import Fonksiyonlar.KitapFonksiyonlari;
import Fonksiyonlar.OgrenciFonksiyonlari;
import java.sql.DriverManager;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Onur Akbal-Emre Ertekin
 */
public class KitapAl extends javax.swing.JFrame {
    /**
     * Creates new form KitapAl
     */
    OgrenciFonksiyonlari ogr = new OgrenciFonksiyonlari();
    KitapFonksiyonlari kitap = new KitapFonksiyonlari();
    public KitapAl() {
        super("Emanet Kitap Teslim Al");
        initComponents();
        ogrenciTable.setModel(DbUtils.resultSetToTableModel(ogr.listele()));
        kitapTable.setModel(DbUtils.resultSetToTableModel(kitap.stokDisiListele()));
        alisverisTable.setModel(DbUtils.resultSetToTableModel(kitap.alisverisListele()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kitapAlPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnAl = new javax.swing.JButton();
        btngeri = new javax.swing.JButton();
        dateteslimtarihi = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        ogrenciTable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        kitapTable = new javax.swing.JTable();
        btnKitapSeç = new javax.swing.JButton();
        btnOgrSec = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        alisverisTable = new javax.swing.JTable();
        secilenOgrenci = new javax.swing.JLabel();
        secilenKitap = new javax.swing.JLabel();
        dataara = new javax.swing.JTextField();
        arabutonu = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        kitapAlPanel.setBackground(new java.awt.Color(210, 218, 226));

        jLabel1.setText("Teslim Tarihi");

        btnAl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconlar/icons8-book-stack-24.png"))); // NOI18N
        btnAl.setText("Teslim Et");
        btnAl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlActionPerformed(evt);
            }
        });

        btngeri.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconlar/icons8-return-24.png"))); // NOI18N
        btngeri.setText("Geri");
        btngeri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btngeriActionPerformed(evt);
            }
        });

        ogrenciTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(ogrenciTable);

        jLabel2.setText("Öğrenciler");

        jLabel3.setText("Kitaplar");

        kitapTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(kitapTable);

        btnKitapSeç.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconlar/icons8-add-book-24.png"))); // NOI18N
        btnKitapSeç.setText("Kitap Seç");
        btnKitapSeç.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKitapSeçActionPerformed(evt);
            }
        });

        btnOgrSec.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconlar/icons8-student-registration-24.png"))); // NOI18N
        btnOgrSec.setText("Öğrenci Seç");
        btnOgrSec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOgrSecActionPerformed(evt);
            }
        });

        alisverisTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(alisverisTable);
        if (alisverisTable.getColumnModel().getColumnCount() > 0) {
            alisverisTable.getColumnModel().getColumn(0).setMinWidth(0);
            alisverisTable.getColumnModel().getColumn(0).setMaxWidth(0);
        }

        dataara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dataaraActionPerformed(evt);
            }
        });

        arabutonu.setText("Ara");
        arabutonu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                arabutonuActionPerformed(evt);
            }
        });

        jLabel4.setText("Arama Çubuğu");

        javax.swing.GroupLayout kitapAlPanelLayout = new javax.swing.GroupLayout(kitapAlPanel);
        kitapAlPanel.setLayout(kitapAlPanelLayout);
        kitapAlPanelLayout.setHorizontalGroup(
            kitapAlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kitapAlPanelLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(kitapAlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kitapAlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(kitapAlPanelLayout.createSequentialGroup()
                            .addComponent(btnOgrSec, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(secilenOgrenci, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel3)
                        .addGroup(kitapAlPanelLayout.createSequentialGroup()
                            .addComponent(btnKitapSeç, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(secilenKitap, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(kitapAlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kitapAlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(kitapAlPanelLayout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addGap(18, 18, 18)
                            .addGroup(kitapAlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(dateteslimtarihi, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(kitapAlPanelLayout.createSequentialGroup()
                                    .addComponent(btnAl)
                                    .addGap(46, 46, 46)
                                    .addComponent(btngeri))))
                        .addGroup(kitapAlPanelLayout.createSequentialGroup()
                            .addGroup(kitapAlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, kitapAlPanelLayout.createSequentialGroup()
                                    .addComponent(dataara, javax.swing.GroupLayout.PREFERRED_SIZE, 468, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(arabutonu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 599, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(8, 8, 8)))
                    .addComponent(jLabel4))
                .addGap(31, 31, 31))
        );
        kitapAlPanelLayout.setVerticalGroup(
            kitapAlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kitapAlPanelLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(kitapAlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kitapAlPanelLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addGroup(kitapAlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnOgrSec)
                            .addComponent(secilenOgrenci))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addGroup(kitapAlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnKitapSeç)
                            .addComponent(secilenKitap)))
                    .addGroup(kitapAlPanelLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(kitapAlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(dataara, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(arabutonu))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addGroup(kitapAlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dateteslimtarihi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(81, 81, 81)
                        .addGroup(kitapAlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAl)
                            .addComponent(btngeri))
                        .addContainerGap())))
        );

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel9.setText("Kitap Teslim Etme");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kitapAlPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(kitapAlPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(52, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlActionPerformed
        // TODO add your handling code here:
        KitapHareketleri hazirla = new KitapHareketleri();
        hazirla.Kit_Id = secilenkit;
        hazirla.Uye_Id = secilenogr;
        
        
        SimpleDateFormat dateFormat = new SimpleDateFormat("dd-MM-yyyy");
        String tarih = dateFormat.format(dateteslimtarihi.getDate());
        hazirla.TeslimTarihi = tarih;
        KitapGuncelle gonder = new KitapGuncelle();
        gonder.guncelle(hazirla);
        alisverisTable.setModel(DbUtils.resultSetToTableModel(kitap.alisverisListele()));
    }//GEN-LAST:event_btnAlActionPerformed

    private void btngeriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btngeriActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        AnaMenu yeni = new AnaMenu();
        yeni.setVisible(true);
    }//GEN-LAST:event_btngeriActionPerformed
    int secilenkit;
    
    private void btnKitapSeçActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKitapSeçActionPerformed
        // TODO add your handling code here:
        int tablosatir= kitapTable.getSelectedRow();//Hangi satır olduğunu alıyor.
        secilenkit=(int) kitapTable.getValueAt(tablosatir,0);
        
        KitapFonksiyonlari getir = new KitapFonksiyonlari();
        Kitapp gelen = getir.kitapGetir(secilenkit);
        secilenKitap.setText("Secilen Kitap: "+gelen.isim);
        JOptionPane.showMessageDialog(null, "Seçilen Kitap: "+gelen.isim);
    }//GEN-LAST:event_btnKitapSeçActionPerformed
    int secilenogr;
    
    private void btnOgrSecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOgrSecActionPerformed
        // TODO add your handling code here:
        int tablosatir= ogrenciTable.getSelectedRow();//Hangi satır olduğunu alıyor.
        secilenogr=(int) ogrenciTable.getValueAt(tablosatir,0);
        
        OgrenciFonksiyonlari getir = new OgrenciFonksiyonlari();
        Uye gelen = getir.ogrenciGetir(secilenogr);
        secilenOgrenci.setText("Secılen Ogrencı: "+gelen.isim);
        JOptionPane.showMessageDialog(null, "Seçilen Öğrenci: "+gelen.isim);
    }//GEN-LAST:event_btnOgrSecActionPerformed

    private void dataaraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dataaraActionPerformed
       
    }//GEN-LAST:event_dataaraActionPerformed

    private void arabutonuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_arabutonuActionPerformed
       DefaultTableModel tablo = (DefaultTableModel)alisverisTable.getModel();
        int rows = tablo.getRowCount();
        String ara = dataara.getText();
        Connection c;
        Statement st ;
        ResultSet rs ;
        for(int i=rows-1;i>=0;i--)
       
        {
            tablo.removeRow(i);
        }
        try
        {
          
            Class.forName("org.sqlite.JDBC");
            c= DriverManager.getConnection("jdbc:sqlite:c:\\Kutuphane\\kutuphane.sqlite");
            st=c.createStatement();
            String query ="SELECT * FROM KitapHareketleri where Ad like '%"+ ara +"%' ";
            
            rs=st.executeQuery(query);
            while(rs.next())
            {
                int idal = rs.getInt("Id");
                int uyeal = rs.getInt("Uye_Id");
                int kital = rs.getInt("Kit_Id");
                String verilis = rs.getString("VerilisTarihi");
                String teslimal = rs.getString("TeslimTarihi");
                String adal = rs.getString("Ad");
                String kitapal = rs.getString("KitapAdi");
                tablo.addRow(new Object[] {idal,uyeal,kital,verilis,teslimal,adal,kitapal});
            }
            
          
        }
        catch(Exception e)
        {
            
        }  
    }//GEN-LAST:event_arabutonuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KitapAl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KitapAl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KitapAl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KitapAl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KitapAl().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable alisverisTable;
    private javax.swing.JButton arabutonu;
    private javax.swing.JButton btnAl;
    private javax.swing.JButton btnKitapSeç;
    private javax.swing.JButton btnOgrSec;
    private javax.swing.JButton btngeri;
    private javax.swing.JTextField dataara;
    private com.toedter.calendar.JDateChooser dateteslimtarihi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JPanel kitapAlPanel;
    private javax.swing.JTable kitapTable;
    private javax.swing.JTable ogrenciTable;
    private javax.swing.JLabel secilenKitap;
    private javax.swing.JLabel secilenOgrenci;
    // End of variables declaration//GEN-END:variables
}
